name: "Terraform Plan"

# Trigger when commits are pushed to the main branch
on:
  push:
    branches:
      - main

jobs:
  terraform-plan:
    name: "Terraform Plan"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./tf
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      STATE_BUCKET: ${{ secrets.STATE_BUCKET }}
      STATE_KEY: ${{ secrets.STATE_KEY }}
      STATE_ENCRYPT: ${{ secrets.STATE_ENCRYPT }}
      STATE_REGION: ${{ secrets.STATE_REGION }}
    steps:
      - name: "Setup - Checkout"
        uses: actions/checkout@v2.1.0
      - name: "Setup - Terraform CLI"
        uses: hashicorp/setup-terraform@v1.3.2
        with:
          terraform_version: 1.0.4
      - name: "Run - Terraform Init"
        run: |
          terraform init -input=false \
            -backend-config="bucket=$STATE_BUCKET" \
            -backend-config="key=$STATE_KEY" \
            -backend-config="encrypt=$STATE_ENCRYPT" \
            -backend-config="region=$STATE_REGION"
      - name: "Run - Terraform Plan"
        run: terraform plan -input=false